#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "helloworld.pb.h"

namespace helloworld
{

namespace Greeter
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void SayHello(HelloRequest *request, HelloReply *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using SayHelloDone = std::function<void (HelloReply *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void SayHello(const HelloRequest *req, SayHelloDone done);
	void SayHello(const HelloRequest *req, HelloReply *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<HelloReply, srpc::RPCSyncContext>> async_SayHello(const HelloRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_SayHello_task(SayHelloDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void SayHello(const HelloRequest *req, SayHelloDone done);
	void SayHello(const HelloRequest *req, HelloReply *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<HelloReply, srpc::RPCSyncContext>> async_SayHello(const HelloRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_SayHello_task(SayHelloDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void SayHello(const HelloRequest *req, SayHelloDone done);
	void SayHello(const HelloRequest *req, HelloReply *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<HelloReply, srpc::RPCSyncContext>> async_SayHello(const HelloRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_SayHello_task(SayHelloDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void SayHello(const HelloRequest *req, SayHelloDone done);
	void SayHello(const HelloRequest *req, HelloReply *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<HelloReply, srpc::RPCSyncContext>> async_SayHello(const HelloRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_SayHello_task(SayHelloDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void SayHello(const HelloRequest *req, SayHelloDone done);
	void SayHello(const HelloRequest *req, HelloReply *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<HelloReply, srpc::RPCSyncContext>> async_SayHello(const HelloRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_SayHello_task(SayHelloDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("helloworld.Greeter")
{
	this->srpc::RPCService::add_method("SayHello",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::SayHello);
		});
}
inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("helloworld.Greeter")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("helloworld.Greeter")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::SayHello(const HelloRequest *req, SayHelloDone done)
{
	auto *task = this->create_rpc_client_task("SayHello", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::SayHello(const HelloRequest *req, HelloReply *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SayHello(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<HelloReply, srpc::RPCSyncContext>> SRPCClient::async_SayHello(const HelloRequest *req)
{
	using RESULT = std::pair<HelloReply, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<HelloReply>("SayHello", srpc::RPCAsyncFutureCallback<HelloReply>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_SayHello_task(SayHelloDone done)
{
	return this->create_rpc_client_task("SayHello", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("helloworld/Greeter")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("helloworld/Greeter")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::SayHello(const HelloRequest *req, SayHelloDone done)
{
	auto *task = this->create_rpc_client_task("SayHello", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::SayHello(const HelloRequest *req, HelloReply *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SayHello(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<HelloReply, srpc::RPCSyncContext>> SRPCHttpClient::async_SayHello(const HelloRequest *req)
{
	using RESULT = std::pair<HelloReply, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<HelloReply>("SayHello", srpc::RPCAsyncFutureCallback<HelloReply>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_SayHello_task(SayHelloDone done)
{
	return this->create_rpc_client_task("SayHello", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("helloworld.Greeter")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("helloworld.Greeter")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::SayHello(const HelloRequest *req, SayHelloDone done)
{
	auto *task = this->create_rpc_client_task("SayHello", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::SayHello(const HelloRequest *req, HelloReply *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SayHello(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<HelloReply, srpc::RPCSyncContext>> BRPCClient::async_SayHello(const HelloRequest *req)
{
	using RESULT = std::pair<HelloReply, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<HelloReply>("SayHello", srpc::RPCAsyncFutureCallback<HelloReply>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_SayHello_task(SayHelloDone done)
{
	return this->create_rpc_client_task("SayHello", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("helloworld.Greeter")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("helloworld.Greeter")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::SayHello(const HelloRequest *req, SayHelloDone done)
{
	auto *task = this->create_rpc_client_task("/helloworld.Greeter/SayHello", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::SayHello(const HelloRequest *req, HelloReply *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SayHello(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<HelloReply, srpc::RPCSyncContext>> TRPCClient::async_SayHello(const HelloRequest *req)
{
	using RESULT = std::pair<HelloReply, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<HelloReply>("/helloworld.Greeter/SayHello", srpc::RPCAsyncFutureCallback<HelloReply>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_SayHello_task(SayHelloDone done)
{
	return this->create_rpc_client_task("/helloworld.Greeter/SayHello", std::move(done));
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("helloworld.Greeter")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("helloworld.Greeter")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::SayHello(const HelloRequest *req, SayHelloDone done)
{
	auto *task = this->create_rpc_client_task("SayHello", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::SayHello(const HelloRequest *req, HelloReply *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SayHello(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<HelloReply, srpc::RPCSyncContext>> TRPCHttpClient::async_SayHello(const HelloRequest *req)
{
	using RESULT = std::pair<HelloReply, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<HelloReply>("SayHello", srpc::RPCAsyncFutureCallback<HelloReply>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_SayHello_task(SayHelloDone done)
{
	return this->create_rpc_client_task("SayHello", std::move(done));
}

} // end namespace Greeter

} // end namespace helloworld

